apiVersion: v1
kind: Service
metadata:
  name: table-search-pre-service-canary
  namespace: shpre
spec:
  type: ClusterIP
  selector:
    app: table-search-pre-canary
    version: v2
  ports:
    - name: tcp80
      port: 80
      protocol: TCP
      targetPort: 3000
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
