apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shprod
  name: table-search-prod-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: table-search-prod-canary
      version: v2
  template:
    metadata:
      labels:
        app: table-search-prod-canary
        version: v2
    spec:
      imagePullSecrets:
        - name: registry-ali-hangzhou
        - name: registry-ali-sh-ee
      containers:
        - name: table-search-prod-canary
          image: atom-sh-registry-vpc.cn-shanghai.cr.aliyuncs.com/mxrag/table-search-prod:20250920142148
          imagePullPolicy: IfNotPresent
          env:
            - name: NACOS_ENABLE
              value: 'true'
            - name: APP_PROFILE
              value: prod
            - name: ENVIRONMENT
              value: prod
            - name: NACOS_ENDPOINT
              value: mse-886eff00-nacos-ans.mse.aliyuncs.com:8848
            - name: NACOS_NAMESPACE
              value: 3f36bb60-6861-4fad-a057-9bb6d9a4e51d
            - name: aliyun_logs_table-search-prod-canary
              value: stdout
            - name: SITE
              value: cn
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "32Mi"
            limits:
              cpu: "1000m"
              memory: "2048Mi"
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 120
