apiVersion: v1
kind: Service
metadata:
  name: table-search-prod-service-canary
  namespace: shprod
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp80
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: table-search-prod-canary
    version: v2
  sessionAffinity: None
  type: ClusterIP
